### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Bogdanp** [imotov/elasticsearch-facet-script#1]
Running ./plugin -install imotov/elasticsearch-facet-script seems to only install it as a _site plugin and passing in the version number (1.0.0-SNAPSHOT) fails b/c it can't find the zip ball for that. How does one go by installing the plugin?

**Comment by Bogdanp** [comment]
I got it to work in the end; just had to compile the jar and place it in the plugins folder :).

**Comment by imotov** [comment]
Thanks for the interest. It's pretty much a work in progress. It's not ready for release yet. That's why release zip is not there. So, building it and installing it manually is the only way to go for now.

**Comment by Bogdanp** [comment]
Is there anything in particular to watch out for when using it? Great job so far!

**Comment by imotov** [comment]
I am not aware of any particular issues besides total lack of documentation. However, I need to mention that this is basically a weekend hack and I didn't have a chance to test it properly or try it on anything significant. I am also not totally happy about the way parameter are passed to the scripts. So, this part might change in the future.
