### ISSUE TITLE
Not working since 0.90.2 (HashedBytesArray constructor)

### ISSUE THREAD

**Issue by pierrre** [imotov/elasticsearch-facet-script#11]
The constructor HashedBytesArray(String) is not available since 0.90.2.

1) NoSuchMethodError[org.elasticsearch.common.bytes.HashedBytesArray.<init>(Ljava/lang/String;)V]2) NoClassDefFoundError[Could not initialize class org.elasticsearch.search.facet.script.InternalScriptFacet]

**Comment by imotov** [comment]
Fixed in v1.1.1
