### ISSUE TITLE
Is it possible to use this with native scripts?

### ISSUE THREAD

**Issue by Meidan** [imotov/elasticsearch-facet-script#13]
I mean writing the map reduce in Java, like in Search scripts.
I tired adding "lang":"native" but it didn't parse.

**Comment by imotov** [comment]
Could you show the example of your request and the error message that you are getting? The `lang` parameter should be on the same level as `map_script` and `reduce_script`.

**Comment by Meidan** [comment]
Right, I've put it in the wrong level. Now it works.
Do you have an example that uses native scripts?

Thanks.

**Comment by imotov** [comment]
No, I don't think I have a facet-script specific example at the moment.

**Comment by Meidan** [comment]
Thanks Igor, I'm still having problems with this, maybe you can help me out at http://stackoverflow.com/questions/18954213/passing-parameters-to-native-reduce-script-of-elasticsearch-facet-script

**Comment by imotov** [comment]
Looks like it's resolved. Closing.
