### ISSUE TITLE
Class path for the scripts?

### ISSUE THREAD

**Issue by mahdeto** [imotov/elasticsearch-facet-script#4]
Hi,

I've been trying to use this plugin to create a top-n count feature, Normally I want to be able to define classes or use existing ones (from a 3rd party lib) in order to do define an entry and put it in a TreeSet for example.

Is there a way to do this?

**Comment by imotov** [comment]
This plugin is using standard scripting framework of elasticsearch. So, the answer really depends on the script engine that you are using. If you are using MVEL, you can simply drop 3rd party libraries to the lib directory of the elasticsearch. If you are using native script, it might be better to deploy 3rd party libraries with your native script plugin.

**Comment by mahdeto** [comment]
Thanks for your prompt response. This worked for me :)
